channels:
- defaults
- bccp
- astropy
- conda-forge

dependencies:
- python=3
- numpy
- scipy
- astropy
- mpi4py
- runtests
- pmesh
- kdcount
- mpsort
- bigfile
- pandas
- dask>=0.14.2
- cachey
- sympy
- numexpr
- corrfunc
- mcfit
- classylss>=0.2
- h5py
- halotools
- fitsio
- matplotlib
- pip
- pip:
  - git+git://github.com/bccp/nbodykit.git@master
